title: Hemanth Raju Koneti
logo: assets/img/pic.jpeg
theme: jekyll-theme-minimal

navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Experience
    url: /experience
